[package]
name = "parachain-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
parachain-template-runtime = { path = "../runtime" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
